#!/bin/bash
#############################################################################
# phpDiveLog                               (c) 2004-2007 by Itzchak Rehberg #
# written by Itzchak Rehberg <izzysoft AT qumran DOT org>                   #
# http://www.izzysoft.de/                                                   #
# ------------------------------------------------------------------------- #
# This program is free software; you can redistribute and/or modify it      #
# under the terms of the GNU General Public License (see doc/LICENSE)       #
# ------------------------------------------------------------------------- #
# Configuration for the shell scripts that create/transfer the PDL data     #
# (divelog_conduit.sh and resync.sh). Keep these files together in the same #
# directory with the conduit.jar!                                           #
#############################################################################

#========================================================[ Configuration ]===
# Locale settings of your PALM (don't mess up with your PCs settings)
PALMLOCALE=de_DE@euro
# location of the Conduit output (must match the confuration in divelog.ini)
LOGDIR=log
# which units to use for the values: imperial|metric|bothunits
UNITS=bothunits
# date format for logging
DATEFORMAT="%Y-%m-%d %H:%M:%S"
# where to log the process - you need write access to that directory!
LOGFILE=./pdltransfer.log
#------------------------------------------------------[ Local Transfers ]---
# Do we use the local transfer? [0|1]
USELOCAL=1
# the location of phpDiveLogs user dir (where the data/ and images/ dirs are)
PDLBASE=/web/divelog/diver/demo
#-----------------------------------------------------[ Remote Transfers ]---
# Do we intend to use SCP transfers? [0|1|2] (0=No,1=SCP,2=RSync)
USESCP=0
# If so, we need the target base directory
SCPBASE=user@machine:/path_to_PDL/diver/demo
# for RSync, specify whether to copy from your local PDL installation (1 - needs
# USELOCAL=1) or from the ADL logdir (2)
RSYNCBASE=1

